---
logging_config: "config/logging-prod.yaml"
io_adapter: "RaspberryPi"
heartbeat_time: 30
feeds:
  - name: "morning"
    hour: 7
    minute: 0
  - name: "evening"
    hour: 16
    minute: 45
  - name: "night"
    hour: 17
    minute: 30
observers:
  - klass: "SpreadsheetUpdater"
    ifttt_event_name: "cat_bot_log"
    ifttt_api_key: "do-not-commit"
